# Generated by Django 4.1.4 on 2022-12-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landhop", "0002_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="author",
        ),
    ]
