# Generated by Django 4.1.4 on 2022-12-28 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("landhop", "0005_city_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=800)),
                ("photo", models.URLField(max_length=500)),
                (
                    "dateCreated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city",
                        to="landhop.city",
                    ),
                ),
            ],
        ),
    ]
