# Generated by Django 4.1.4 on 2022-12-29 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("landhop", "0006_sight"),
    ]

    operations = [
        migrations.AddField(
            model_name="sight",
            name="totalStars",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                ("stars", models.FloatField()),
                (
                    "dateCreated",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sight",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sight",
                        to="landhop.sight",
                    ),
                ),
            ],
        ),
    ]
